project_name: seristack
builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/seristack 
    binary: seristack
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64 
      - arm64
brews:
  - repository:
      owner: TechXploreLabs
      name: homebrew-tap
    directory: Formula
    homepage: https://github.com/TechXploreLabs/seristack
    description: Seristack is a lightweight automation engine designed to bridge the gap between local task execution and remote triggers. Define your stacks in YAML, manage dependencies, and expose your automation via a built-in HTTP server.
    license: Apache 2.0
