project_name: seristack
builds:
  - env:
    - CGO_ENABLED=0
    main: ./cmd/seristack 
    binary: seristack
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64 
      - arm64